update to modern podman from depraced docker...
make -> error:
WARNING: MongoDB Connection Error:  { MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Timeout.waitQueueMember.timer.setTimeout [as _onTimeout] (/app/node_modules/mongodb/lib/core/sdam/topology.js:430:30)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'MongoServerSelectionError',
  reason:
   TopologyDescription {
     type: 'Single',
     setName: null,
     maxSetVersion: null,
     maxElectionId: null,
     servers: Map { 'mongodb:27017' => [ServerDescription] },
     stale: false,
     compatible: true,
     compatibilityError: null,
     logicalSessionTimeoutMinutes: null,
     heartbeatFrequencyMS: 10000,
     localThresholdMS: 15,
     commonWireVersion: null } }
WARNING: without MongoDB some features (such as backfilling/simulation) may be disabled.
Attempted authentication string: mongodb://mongodb:27017/zenbot4?
/app/lib/services/collection-service.js:18
      return conf.db.mongo.collection('sessions')
                     ^

TypeError: Cannot read property 'mongo' of undefined
    at Object.getSessions (/app/lib/services/collection-service.js:18:22)
    at Command.<anonymous> (/app/commands/trade.js:450:48)
    at Command.listener [as _actionHandler] (/app/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/app/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/app/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/app/node_modules/commander/index.js:882:12)
    at Command.parse (/app/node_modules/commander/index.js:717:10)
    at /app/zenbot.js:46:13
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)